### PR TITLE
Update public repo to match internal repo's 3/8/17 state

### PR DESCRIPTION
**Pull request by bc-mkatz**
@ICarpenter, @bookernath, @becomevocal: Before anyone merges, someone (Ian is first nominee) please carefully inspect to make sure the refreshed v3-catalog.md looks appropriate. Changes here:
* Refreshed YAML file, to match internal version as of 3/8/17.
* Tweaked readme.md, to omit “Catalog” restriction.
* Refreshed v3-catalog.md, by embedding HTML export of new swagger.
* Groomed v3-catalog.md to acknowledge non-Catalog content, add links,
remove duplicate headings.

### CODE REVIEW

**Comment by bc-mkatz** [comment]
Let me see if we have links to the old name...

**Comment by bc-mkatz** [comment]
Can do, but would need to reset inbound links from these files:
/README.md
/docs/v3-catalog.md
Not sure if I'm overlooking any links in the wild? Also, @bc-AlyssNoland/@bookernath, would this name change require significant changes in the Widdershins transformation script?

**Comment by bc-mkatz** [comment]
@bc-jz, @ICarpenter: Please inspect this last commit, it might be the charm for each of you...
- JZON: I re-ran the manual search/replace passes that produced readable line breaks in the currently-published version. Also, this time I systematically inserted a **Properties:** subhead to fill the gap between each description field and its subsequent properties set. Please spot-check whether the results look consistently good. If so, I'll get Nathan to bake these additions into our Python transformation script (when he returns next week).
- Ian: I've renamed `swagger/v3-catalog.yaml` to `swagger/v3-api.yaml`, as you suggested. Please check whether I've properly reset all inbound links to that file?

If we're sure we're in gravy, I think we could merge this. Thanks.

**Comment by bc-jz** [comment]
Cool, thanks @bc-mkatz .  The spacing is looking good to me and I like the addition of "Properties" in there.

I think this is ready to go.

**Comment by ICarpenter** [comment]
👍 looks right to me

**Pull request merged**
